version: '3.8'
services:
  mongo:
    container_name: fitx_api_db
    image: mongo:7.0.5
    user: ${PUID}:${PGID}
    ports:
      - 7003:27017
    volumes:
      - ./mongodata:/data/db
  node:
    container_name: fitx_api
    build: .
    user: ${PUID}:${PGID}
    ports:
      - 7002:5000
    links:
      - mongo